import pandas as pd
import re
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

fortune_500_names = {
    "WALMART":["WAL-MART STORES INC"],
    "EXXONMOBIL":["EXXON MOBIL CORPORATION","EXXON MOBILE","EXXON USA","EXXONMOBIL CHEMICAL CO"],
    "APPLE":["APPLE INC."],
    "BERKSHIRE HATHAWAY":["BERKSHIRE HATHAWAY ENERGY","BERKSHIRE CAPITAL MANAGEMENT CO., INC."],
    "AMAZON":["AMAZON.COM (FRA PILLPACK AN AMAZON COMPANY)","AMAZON.COM SERVICES LLC","AMAZON WEB SERVICES"],
    "UNITED HEALTH GROUP":["UNITEDHEALTH GROUP","INGENIX / UNITEDHEALTH GROUP"],
    "MCKESSON":["MCKESSON CORPORATION"],
    "CVS HEALTH":["CVS HEALTH"],
    "AT&T":["AT&T","ANDERSON & BAKER (AT&T)"],
    "AMERISOURCEBERGEN":["AMERISOURCEBERGEN CORPORATION"],
    "FORD":["FORD MOTOR COMPANY"],
    "GENERAL MOTORS": ["GENERAL MOTORS COMPANY","DUTKO GRAYLING ON BEHALF OF GENERAL MOTORS","SATURN CORPORATION C/O GENERAL MOTORS CORPORATION","GENERAL MOTORS ACCEPTANCE CORP"],
    "COSTCO": ["COSTCO WHOLESALE CORPORATION"],
    "ALPHABET": ["GOOGLE, INC.", "PUBLIC POLICY PARTNERS (GOOGLE INC)","GOOGLE CLOUD"],
    "CARDINAL HEALTH": ["CARDINAL HEALTH","THORSEN FRENCH ADVOCACY ON BEHALF OF CARDINAL HEALTH INC"],
    "WALGREENS BOOTS ALLIANCE": ["WALGREEN CO.","WALGREENS BOOTS ALLIANCE"],
    "JPMORGAN CHASE & CO.": ["JPMORGAN CHASE & CO.","JPMORGAN CHASE HOLDINGS LLC", "JP MORGAN CHASE HOLDINGS"],
    "VERIZON":["VERIZON COMMUNICATIONS","CAUTHEN FORBES & WILLIAMS ON BEHALF OF VERIZON","TELESECTOR RESOURCES INC D/B/A VERIZON SERVICES GROUP INC","MICKEY IBARRA & ASSOC (VERIZON COMMUNICATIONS)"],
    "KROGER":["THE KROGER CO."],
    "GENERAL ELECTRIC": ["GENERAL ELECTRIC COMPANY","ENERAL ELECTRIC APPLIANCES","GENERAL ELECTRIC TRANSPORTATION"],
    "CHEVRON":["CHEVRON","CHEVRON TEXACO","CHEVRONTEXACO INC","CHEVRON PHILLIPS CHEMICAL COMPANY LP","CHEVRON CHEMICAL CO LLC -- ORONITE ADDITIVES DIVISION"],
    "FANNIE MAE":["FANNIE MAE"],
    "PHILLIPS 66":["PHILLIPS 66"],
    "VALERO ENERGY":["VALERO ENERGY", "VALERO ENERGY CORPORATION"],
    "BANK OF AMERICA":["BANK OF AMERICA","THE SMITH-FREE GROUP (ON BEHALF OF BANK OF AMERICA)"],
    "MICROSOFT":["MICROSOFT","MICROSOFT CORPORATION"],
    "HOME DEPOT":["HOME DEPOT"],
    "BOEING":["BOEING","BOEING-SVS INC","AVIATION PARTNERS BOEING","BOEING EMPLOYEES' CREDIT UNION","BOEING COMPANY"],
    "WELLS FARGO":["WELLS FARGO","WELLS FARGO ADVISORS, LLC","WELLS FARGO & COMPANY"],
    "CITIGROUP":["CITIGROUP","TWINLOGIC (ON BEHALF OF CITIGROUP MANAGEMENT CORP.)"],
    "MARATHON PETROLEUM":["MARATHON PETROLEUM" "MARATHON PETROLEUM CORPORATION"],
    "COMCAST":["COMCAST","COMCAST CORP (THROUGH FTI GOVERNMENT AFFAIRS)","COMCAST CORPORATION"],
    "ANTHEM":["ANTHEM","ANTHEM ONE, INC","ANTHEM INC"],
    "DELL TECHNOLOGIES":["DELL TECHNOLOGIES","EMC CORPORATION"],
    "DUPONT DE NEMOURS":["DUPONT DE NEMOURS", "DUPONT"],
    "STATE FARM INSURANCE":["STATE FARM INSURANCE","STATE FARM INSURANCE COMPANIES","NATL ASSN OF STATE FARM AGENTS"],
    "JOHNSON & JOHNSON":["JOHNSON & JOHNSON","JOHNSON & JOHNSON INC"],
    "IBM":["IBM","IBM(FORMERLY HEALTHLINK INC)"],
    "TARGET":["TARGET", "TARGET CORPORATION"],
    "FREDDIE MAC":["FREDDIE MAC"],
    "UNITED PARCEL SERVICE":["UPS", "UNITED PARCEL SERVICE","C2 GROUP (ON BEHALF OF UNITED PARCEL SERVICE)","DOTCHIN & ASSOCIATES ON BEHALF OF UNITED PARCEL SERVICE","RAFFANIELLO & ASSOCIATES ON BEHALF OF UNITED PARCEL SERVICE"],
    "LOWE'S":["LOWE'S","LOWE'S COMPANIES INC."],
    "INTEL":["INTEL","INTEL CORPORATION"],
    "METLIFE":["METLIFE"],
    "PROCTER & GAMBLE":["PROCTER & GAMBLE","PROCTER & GAMBLE INC (ALLIANCE FOR BETTER BONE HEALTH)"],
    "UNITED TECHNOLOGIES":["UNITED TECHNOLOGIES"],
    "FEDEX":["FEDEX","FEDEX CORPORATION","FEDEX CORPORATION (THROUGH O'MELVENY & MYERS LLP)"],
    "PEPSICO":["PEPSICO"],
    "ARCHER DANIELS MIDLAND":["ARCHER DANIELS MIDLAND","ARCHER DANIELS MIDLAND COMPANY"],
    "PRUDENTIAL FINANCIAL":["PRUDENTIAL FINANCIAL","PRUDENTIAL PLC"],
    "CENTENE":["CENTENE","CENTENE CORPORATION"],
    "ALBERTSONS":["ALBERTSONS","ALBERTSONS COMPANIES, INC."],
    "WALT DISNEY":["WALT DISNEY","THE WALT DISNEY COMPANY"],
    "SYSCO":["SYSCO","SYSCO CORP"],
    "HP":["HP", "HEWLETT PACKARD ENTERPRISE COMPANY"],
    "HUMANA":["HUMANA","HUMANA MILITARY"],
    "FACEBOOK":["FACEBOOK"],
    "CATERPILLAR":["CATERPILLAR","CATERPILLAR INC","CATERPILLAR DEFENSE PRODUCTS"],
    "ENERGY TRANSFER":["ENERGY TRANSFER"],
    "LOCKHEED MARTIN":["LOCKHEED MARTIN","LOCKHEED MARTIN CORPORATION","LOCKHEED MARTIN HANFORD","LOCKHEED MARTIN VENTURE STAR","SENECA GROUP LLC ON BEHALF OF LOCKHEED MARTIN"],
    "PFIZER":["PFIZER","PFIZER AUSTRALIA PTY LTD","ALPHARMA INC/PFIZER ANIMAL HEALTH (FORMERLY KNOWN AS ALPHARMA INC )"],
    "GOLDMAN SACHS GROUP":["GOLDMAN SACHS GROUP","GOLDMAN SACHS & CO"],
    "MORGAN STANLEY":["MORGAN STANLEY","MORGAN STANLEY DEAN WITTER"],
    "CISCO SYSTEMS":["CISCO SYSTEMS","CISCO SYSTEMS, INC."],
    "CIGNA":["CIGNA","THE CIGNA GROUP AND SUBSIDIARIES","CIGNA CORPORATION"],
    "AIG":["AIG","AIG SHAREHOLDERS GROUP (AD HOC COALITION)","AIG TECHNICAL SERVICES"],
    "HCA HEALTHCARE":["HCA HEALTHCARE","HCA-HEALTHONE LLC DBA ROSE MEDICAL CENTER"],
    "AMERICAN AIRLINES GROUP":["AMERICAN AIRLINES GROUP","AMERICAN AIRLINES"],
    "DELTA AIR LINES":["DELTA AIR LINES"],
    "CHARTER COMMUNICATIONS":["CHARTER COMMUNICATIONS"],
    "NEW YORK LIFE INSURANCE":["NEW YORK LIFE INSURANCE","NEW YORK LIFE INSURANCE COMPANY"],
    "AMERICAN EXPRESS":["AMERICAN EXPRESS","AMERICAN EXPRESS COMPANY"],
    "NATIONWIDE":["NATIONWIDE","NATIONWIDE GLOBAL","NATIONWIDE INSURANCE"],
    "BEST BUY":["BEST BUY"],
    "LIBERTY MUTUAL INSURANCE GROUP":["LIBERTY MUTUAL INSURANCE GROUP","LIBERTY MUTUAL GROUP","LIBERTY MUTUAL INSURANCE"],
    "MERCK":["MERCK","CAUTHEN FORBES & WILLIAMS ON BEHALF OF MERCK","MERCK-MEDCO MANAGED CARE","MERCK & CO"],
    "HONEYWELL INTERNATIONAL":["HONEYWELL INTERNATIONAL","INTELLIGRATED SYSTEMS, INC. DBA HONEYWELL INTELLIGRATED","HONEYWELL INTERNATIONAL"],
    "UNITED CONTINENTAL HOLDINGS":["UNITED CONTINENTAL HOLDINGS"],
    "TIAA":["TIAA","THE LIVINGSTON GROUP (ON BEHALF OF TIAA-CREF)"],
    "TYSON FOODS":["TYSON FOODS","TYSON FOODS INC"],
    "ORACLE":["ORACLE","ORACLE CORPORATION"],
    "ALLSTATE":["ALLSTATE","ALLSTATE INSURANCE COMPANY"],
    "WORLD FUEL SERVICES":["WORLD FUEL SERVICES","WORLD FUEL SERVICES CORP"],
    "MASSACHUSETTS MUTUAL LIFE INSURANCE":["MASSACHUSETTS MUTUAL LIFE INSURANCE","MASSACHUSETTS MUTUAL LIFE INSURANCE COMPANY"],
    "TJX":["TJX","TJX COS INC"],
    "CONOCOPHILLIPS":["CONOCOPHILLIPS"],
    "DEERE":["DEERE","JOHN DEERE"],
    "TECH DATA":["TECH DATA"],
    "ENTERPRISE PRODUCTS PARTNERS":["ENTERPRISE PRODUCTS PARTNERS", "ENTERPRISE PRODUCTS OPERATING LLC"],
    "NIKE":["NIKE","NIKE, INC."],
    "PUBLIX SUPER MARKETS":["PUBLIX SUPER MARKETS","PUBLIX SUPER MARKETS, INC."],
    "GENERAL DYNAMICS":["GENERAL DYNAMICS","GENERAL DYNAMICS ARMAMENT SYSTEMS - SACO OPERATIONS"],
    "EXELON":["EXELON","EXELON CORPORATION"],
    "PLAINS GP HOLDINGS":["PLAINS GP HOLDINGS"],
    "3M":["3M","MINNESOTA MINING AND MANUFACTURING COMPANY (3M) ON BEHALF OF AKIN GUMP","3M COMPANY"],
    "ABBVIE":["ABBVIE"],
    "CHS":["CHS"],
    "CAPITAL ONE FINANCIAL":["CAPITAL ONE FINANCIAL","CAPITAL ONE FINANCIAL CORPORATION"],
    "PROGRESSIVE":["PROGRESSIVE"],
    "COCA-COLA":["COCA-COLA","THE COCA-COLA COMPANY"],
    "USAA":["USAA"],
    "HEWLETT PACKARD ENTERPRISE":["HEWLETT PACKARD ENTERPRISE","HEWLETT PACKARD ENTERPRISE COMPANY"],
    "ABBOTT LABORATORIES":["ABBOTT LABORATORIES", "ROSS ABBOTT LABS","ABBOTT DIABETES CARE"],
    "TWENTY-FIRST CENTURY FOX":["TWENTY-FIRST CENTURY FOX", "FOX CORPORATION","21ST CENTURY FOX"],
    "MICRON TECHNOLOGY":["MICRON TECHNOLOGY","MICRON TECHNOLOGY, INC."],
    "TRAVELERS":["TRAVELERS","THE TRAVELERS COMPANIES, INC. AND SUBSIDIARIES"],
    "RITE AID":["RITE AID","RITE AID CORPORATION"],
    "NORTHROP GRUMMAN":["NORTHROP GRUMMAN","NORTHROP GRUMMAN CORPORATION"],
    "ARROW ELECTRONICS":["ARROW ELECTRONICS"],
    "PHILIP MORRIS INTERNATIONAL":["PHILIP MORRIS INTERNATIONAL"],
    "NORTHWESTERN MUTUAL":["NORTHWESTERN MUTUAL","THE NORTHWESTERN MUTUAL LIFE INSURANCE COMPANY"],
    "INTL FCSTONE":["INTL FCSTONE","INTL FCSTONE INC."],
    "PBF ENERGY":["PBF ENERGY"],
    "RAYTHEON":["RAYTHEON","RAYTHEON COMPANY"],
    "KRAFT HEINZ":["KRAFT HEINZ"],
    "MONDELEZ INTERNATIONAL":["MONDELEZ INTERNATIONAL","MONDELEZ GLOBAL LLC"],
    "U.S. BANCORP":["U.S. BANCORP"],
    "MACY'S":["MACY'S","MACY'S INC."],
    "DOLLAR GENERAL":["DOLLAR GENERAL","DOLLAR GENERAL CORPORATION"],
    "NUCOR":["NUCOR","NUCOR CORPORATION"],
    "STARBUCKS":["STARBUCKS","STARBUCKS CORPORATION"],
    "DXC TECHNOLOGY":["DXC TECHNOLOGY"],
    "ELI LILLY":["ELI LILLY","ELI LILLY AND COMPANY"],
    "THERMO FISHER SCIENTIFIC":["THERMO FISHER SCIENTIFIC","BLUEBIRD STRATEGIES (ON BEHALF OF THERMO FISHER SCIENTIFIC)","HAMILTON PLACE STRATEGIES (ON BEHALF OF THERMO FISHER SCIENTIFIC)"],
    "US FOODS HOLDING":["US FOODS HOLDING"],
    "DUKE ENERGY":["DUKE ENERGY"],
    "HALLIBURTON":["HALLIBURTON","HALLIBURTON COMPANY"],
    "CUMMINS":["CUMMINS","CUMMINS-ALLISON CORPORATION"],
    "AMGEN":["AMGEN"],
    "PACCAR":["PACCAR"],
    "SOUTHERN":["SOUTHERN"],
    "CENTURYLINK":["CENTURYLINK"],
    "INTERNATIONAL PAPER":["INTERNATIONAL PAPER","INTERNATIONAL PAPER COMPANY"],
    "UNION PACIFIC":["UNION PACIFIC"],
    "DOLLAR TREE":["DOLLAR TREE","DOLLAR TREE STORES INC"],
    "PENSKE AUTOMOTIVE GROUP":["PENSKE AUTOMOTIVE GROUP"],
    "QUALCOMM":["QUALCOMM","QUALCOMM INCORPORATED","PAUL, WEISS, RIFKIND, WHARTON & GARRISON LLP ON BEHALF OF QUALCOMM INCORPORATED"],
    "BRISTOL-MYERS SQUIBB":["BRISTOL-MYERS SQUIBB","BRISTOL-MYERS SQUIBB CO"],
    "GILEAD SCIENCES":["GILEAD SCIENCES","GILEAD SCIENCES, INC."],
    "JABIL":["JABIL","JABIL, INC."],
    "MANPOWERGROUP":["MANPOWERGROUP"],
    "SOUTHWEST AIRLINES":["SOUTHWEST AIRLINES","SOUTHWEST AIRLINES PILOTS' ASSOCIATION","MCCARTHY ADVANCED CONSULTING, LLC (ON BEHALF OF SOUTHWEST AIRLINES PILOTS ASSN.)"],
    "AFLAC":["AFLAC"],
    "TESLA":["TESLA","TESLA, INC.","TESLA LABORATORIES"],
    "AUTONATION":["AUTONATION"],
    "CBRE GROUP":["CBRE GROUP"],
    "LEAR":["LEAR","LEAR CORPORATION"],
    "WHIRLPOOL":["WHIRLPOOL","WHIRLPOOL CORPORATION"],
    "MCDONALD'S":["MCDONALD'S","MCDONALD'S CORPORATION"],
    "BROADCOM":["BROADCOM","BROADCOM INC."],
    "MARRIOTT INTERNATIONAL":["MARRIOTT INTERNATIONAL","MARRIOTT INTERNATIONAL, INC."],
    "WESTERN DIGITAL":["WESTERN DIGITAL","WESTERN DIGITAL CORPORATION"],
    "VISA":["VISA"],
    "LENNAR":["LENNAR","LENNAR CORPORATION"],
    "WELLCARE HEALTH PLANS":["WELLCARE HEALTH PLANS","WELLCARE HEALTH PLANS, INC."],
    "KOHL'S":["KOHL'S","KOHL'S DEPARTMENT STORES, INC."],
    "AECOM":["AECOM","ALPINE GROUP, INC. ON BEHALF OF AECOM"],
    "SYNNEX":["SYNNEX"],
    "PNC FINANCIAL SERVICES":["PNC FINANCIAL SERVICES","THE PNC FINANCIAL SERVICES GROUP"],
    "DANAHER":["DANAHER","DANAHER CORPORATION"],
    "HARTFORD FINANCIAL SERVICES":["HARTFORD FINANCIAL SERVICES","HARTFORD FINANCIAL SERVICES GROUP"],
    "ALTRIA GROUP":["ALTRIA GROUP","ALTRIA CLIENT SERVICES LLC"],
    "BANK OF NEW YORK MELLON":["BANK OF NEW YORK MELLON"],
    "FLUOR":["FLUOR","FLUOR CORPORATION"],
    "AVNET":["AVNET"],
    "ICAHN ENTERPRISES":["ICAHN ENTERPRISES","ICAHN INSTITUTE FOR GENOMICS AND MULTISCALE BIOLOGY","ICAHN ASSOCIATES LLC"],
    "OCCIDENTAL PETROLEUM":["OCCIDENTAL PETROLEUM","OCCIDENTAL PETROLEUM CORPORATION"],
    "MOLINA HEALTHCARE":["MOLINA HEALTHCARE","MOLINA HEALTHCARE, INC."],
    "GENUINE PARTS":["GENUINE PARTS"],
    "FREEPORT-MCMORAN":["FREEPORT-MCMORAN","FM SERVICES COMPANY (FREEPORT MCMORAN)"],
    "KIMBERLY-CLARK":["KIMBERLY-CLARK","KIMBERLY-CLARK CORPORATION"],
    "TENET HEALTHCARE":["TENET HEALTHCARE","TENET HEALTHCARE CORPORATION"],
    "SYNCHRONY FINANCIAL":["SYNCHRONY FINANCIAL"],
    "CARMAX":["CARMAX","CARMAX INC"],
    "HOLLYFRONTIER":["HOLLYFRONTIER","HAUCK STRATEGIES, LLC (OBO HOLLYFRONTIER CORPORATION)"],
    "PERFORMANCE FOOD GROUP":["PERFORMANCE FOOD GROUP"],
    "SHERWIN-WILLIAMS":["SHERWIN-WILLIAMS","THE SHERWIN-WILLIAMS COMPANY"],
    "EMERSON ELECTRIC":["EMERSON ELECTRIC","EMERSON ELECTRIC CO."],
    "NGL ENERGY PARTNERS":["NGL ENERGY PARTNERS"],
    "XPO LOGISTICS":["XPO LOGISTICS","WIGGIN AND DANA LLP (ON BEHALF OF XPO LOGISTICS, INC.)"],
    "EOG RESOURCES":["EOG RESOURCES"],
    "APPLIED MATERIALS":["APPLIED MATERIALS","APPLIED MATERIALS, INC."],
    "PG&E":["PG&E"],
    "NEXTERA ENERGY":["NEXTERA ENERGY","NEXTERA ENERGY, INC."],
    "C.H. ROBINSON WORLDWIDE":["C.H. ROBINSON WORLDWIDE","C.H. ROBINSON WORLDWIDE, INC."],
    "GAP":["GAP","GAP INC."],
    "LINCOLN NATIONAL":["LINCOLN NATIONAL"],
    "DAVITA":["DAVITA","DAVITA INC"],
    "JONES LANG LASALLE":["JONES LANG LASALLE","JONES LANG LASALLE AMERICAS INC"],
    "WESTROCK":["WESTROCK","WESTROCK (FORMERLY ROCKTENN)"],
    "CDW":["CDW"],
    "AMERICAN ELECTRIC POWER":["AMERICAN ELECTRIC POWER"],
    "COGNIZANT TECHNOLOGY SOLUTIONS":["COGNIZANT TECHNOLOGY SOLUTIONS"],
    "D.R. HORTON":["D.R. HORTON"],
    "BECTON DICKINSON":["BECTON DICKINSON","BECTON, DICKINSON AND COMPANY"],
    "NORDSTROM":["NORDSTROM"],
    "NETFLIX":["NETFLIX","NETFLIX, INC."],
    "ARAMARK":["ARAMARK"],
    "TEXAS INSTRUMENTS":["TEXAS INSTRUMENTS","TEXAS INSTRUMENTS INCORPORATED"],
    "GENERAL MILLS":["GENERAL MILLS"],
    "SUPERVALU":["SUPERVALU","SUPERVALU INC"],
    "COLGATE-PALMOLIVE":["COLGATE-PALMOLIVE","COLGATE-PALMOLIVE CO"],
    "GOODYEAR TIRE & RUBBER":["GOODYEAR TIRE & RUBBER","THE GOODYEAR TIRE & RUBBER COMPANY","RETIREES OF THE GOODYEAR TIRE & RUBBER COMPANY HEALTH CARE TRUST"],
    "PAYPAL HOLDINGS":["PAYPAL HOLDINGS","PAYPAL"],
    "PPG INDUSTRIES":["PPG INDUSTRIES","PPG INDUSTRIES, INC."],
    "OMNICOM GROUP":["OMNICOM GROUP"],
    "CELGENE":["CELGENE","CELGENE CORPORATION"],
    "JACOBS ENGINEERING GROUP":["JACOBS ENGINEERING GROUP"],
    "ROSS STORES":["ROSS STORES"],
    "MARSH & MCLENNAN":["MARSH & MCLENNAN","MARSH & MCLENNAN COMPANIES, INC."],
    "MASTERCARD":["MASTERCARD","MASTERCARD WORLDWIDE","TOWER 19 ON BEHALF OF MASTERCARD INC.","FTI GOVERNMENT AFFAIRS ON BEHALF OF MASTERCARD"],
    "LAND O'LAKES":["LAND O'LAKES","LAND O'LAKES INC"],
    "WASTE MANAGEMENT":["WASTE MANAGEMENT","ADVANTEK WASTE MANAGEMENT SERVICES LLC"],
    "ILLINOIS TOOL WORKS":["ILLINOIS TOOL WORKS"],
    "ECOLAB":["ECOLAB"],
    "BOOKING HOLDINGS":["BOOKING HOLDINGS","BOOKING HOLDINGS INC. F/K/A/BOOKING.COM CONSULTING SERVICES (USA), INC."],
    "CBS":["CBS","CBS CORPORATION"],
    "PARKER-HANNIFIN":["PARKER-HANNIFIN"],
    "PRINCIPAL FINANCIAL":["PRINCIPAL FINANCIAL","PRINCIPAL FINANCIAL GROUP"],
    "DTE ENERGY":["DTE ENERGY"],
    "BLACKROCK":["BLACKROCK","BLACKROCK FUND SERVICES GROUP, LLC","BLACKROCK MICROSYSTEMS"],
    "UNITED STATES STEEL":["UNITED STATES STEEL","UNITED STATES STEEL CORPORATION"],
    "COMMUNITY HEALTH SYSTEMS":["COMMUNITY HEALTH SYSTEMS"],
    "KINDER MORGAN":["KINDER MORGAN"],
    "QURATE RETAIL":["QURATE RETAIL","QURATE RETAIL INC F/K/A LIBERTY INTERACTIVE CORPORATION"],
    "LOEWS":["LOEWS","LOEWS CORPORATION"],
    "ARCONIC":["ARCONIC","HOWMET AEROSPACE INC FORMALLY KNOWN AS ARCONIC INC"],
    "STANLEY BLACK & DECKER":["STANLEY BLACK & DECKER"],
    "TEXTRON":["TEXTRON","TEXTRON INC."],
    "LAS VEGAS SANDS":["LAS VEGAS SANDS","LAS VEGAS SANDS CORPORATION"],
    "ESTEE LAUDER":["ESTEE LAUDER","THE ESTEE LAUDER COMPANIES, INC"],
    "DISH NETWORK":["DISH NETWORK","DISH NETWORK LLC"],
    "STRYKER":["STRYKER","STRYKER CORPORATION"],
    "KELLOGG":["KELLOGG", "KELLOGG CO", "KELLANOVA F/K/A KELLOGG COMPANY"],
    "BIOGEN":["BIOGEN"],
    "ALCOA":["ALCOA"],
    "ANADARKO PETROLEUM":["ANADARKO PETROLEUM","ANADARKO PETROLEUM CORPORATION (FORMERLY KERR MCGEE CORPORATION)"],
    "DOMINION ENERGY":["DOMINION ENERGY"],
    "ADP":["ADP","FUNDACION ACCION DEMOCRATICO PUERTORRIQUENA (ADP)"],
    "SALESFORCE.COM":["SALESFORCE.COM","SALESFORCE.COM, INC."],
    "L BRANDS":["L BRANDS","L BRANDS INC FORMERLY KNOWN AS LIMITED BRANDS INC"],
    "HENRY SCHEIN":["HENRY SCHEIN"],
    "NEWELL BRANDS":["NEWELL BRANDS","NEWELL BRANDS INC."],
    "GUARDIAN LIFE INS. CO. OF AMERICA":["GUARDIAN LIFE INS. CO. OF AMERICA","GUARDIAN LIFE INSURANCE COMPANY OF AMERICA"],
    "BJ'S WHOLESALE CLUB":["BJ'S WHOLESALE CLUB"],
    "BB&T CORP.":["BB&T CORP."],
    "STATE STREET CORP.":["STATE STREET CORP."],
    "VIACOM":["VIACOM","AMERICAN CONTINENTAL GROUP ON BEHALF OF VIACOM"],
    "AMERIPRISE FINANCIAL":["AMERIPRISE FINANCIAL"],
    "CORE-MARK HOLDING":["CORE-MARK HOLDING"],
    "REINSURANCE GROUP OF AMERICA":["REINSURANCE GROUP OF AMERICA"],
    "VF":["VF","VF SERVICES, LLC"],
    "DISCOVER FINANCIAL SERVICES":["DISCOVER FINANCIAL SERVICES"],
    "GLOBAL PARTNERS":["GLOBAL PARTNERS"],
    "EDISON INTERNATIONAL":["EDISON INTERNATIONAL"],
    "ONEOK":["ONEOK","ONEOK, INC."],
    "MURPHY USA":["MURPHY USA"],
    "BED BATH & BEYOND":["BED BATH & BEYOND"],
    "CONSOLIDATED EDISON":["CONSOLIDATED EDISON"," CONSOLIDATED EDISON SOLUTIONS, INC."],
    "CSX":["CSX", "CSX CORPORATION","CSX WORLD TERMINALS"],
    "J.C. PENNEY":["J.C. PENNEY"],
    "LKQ":["LKQ","LKQ CORPORATION"],
    "FIRSTENERGY":["FIRSTENERGY"],
    "STEEL DYNAMICS":["STEEL DYNAMICS","STEEL DYNAMICS INC"],
    "LITHIA MOTORS":["LITHIA MOTORS"],
    "MGM RESORTS INTERNATIONAL":["MGM RESORTS INTERNATIONAL"],
    "TENNECO":["TENNECO"],
    "NVIDIA":["NVIDIA","NVIDIA CORPORATION"],
    "SEMPRA ENERGY":["SEMPRA ENERGY"],
    "FARMERS INSURANCE EXCHANGE":["FARMERS INSURANCE EXCHANGE"],
    "BALL":["BALL"],
    "GROUP 1 AUTOMOTIVE":["GROUP 1 AUTOMOTIVE"],
    "UNUM GROUP":["UNUM GROUP"],
    "XCEL ENERGY":["XCEL ENERGY"],
    "RELIANCE STEEL & ALUMINUM":["RELIANCE STEEL & ALUMINUM"],
    "HUNTSMAN":["HUNTSMAN","HUNTSMAN CORPORATION"],
    "NORFOLK SOUTHERN":["NORFOLK SOUTHERN","NORFOLK SOUTHERN CORPORATION"],
    "LABORATORY CORP. OF AMERICA":["LABORATORY CORP. OF AMERICA"],
    "CORNING":["CORNING","CORNING INC"],
    "EXPEDIA GROUP":["EXPEDIA GROUP"],
    "AUTOZONE":["AUTOZONE"],
    "W.W. GRAINGER":["W.W. GRAINGER","W.W. GRAINGER, INC."],
    "QUANTA SERVICES":["QUANTA SERVICES","DMM STRATEGIES ON BEHALF OF QUANTA SERVICES","QUANTA SERVICES, INC."],
    "CROWN HOLDINGS":["CROWN HOLDINGS","STRATHSPEY CROWN HOLDINGS, LLC"],
    "OFFICE DEPOT":["OFFICE DEPOT"],
    "BAXTER INTERNATIONAL":["BAXTER INTERNATIONAL"],
    "LAM RESEARCH":["LAM RESEARCH","LAM RESEARCH CORP."],
    "ENTERGY":["ENTERGY","ENTERGY SERVICES LLC"],
    "CHARLES SCHWAB":["CHARLES SCHWAB","CHARLES SCHWAB & CO INC"],
    "L3 TECHNOLOGIES":["L3 TECHNOLOGIES"],
    "NRG ENERGY":["NRG ENERGY","PETRA NOVA, A SUBSIDIARY OF NRG ENERGY, INC.","NRG ENERGY, INC."],
    "LIVE NATION ENTERTAINMENT":["LIVE NATION ENTERTAINMENT"],
    "UNIVERSAL HEALTH SERVICES":["UNIVERSAL HEALTH SERVICES"],
    "MOLSON COORS BREWING":["MOLSON COORS BREWING"],
    "EBAY":["EBAY","EBAY INC."],
    "AES":["AES","AES DRILLING FLUIDS, LLC","AES SPARROWS POINT LNG","AES TELECOM"],
    "DEVON ENERGY":["DEVON ENERGY","DEVON ENERGY CORPORATION"],
    "PACIFIC LIFE":["PACIFIC LIFE","PACIFIC LIFE INSURANCE COMPANY"],
    "CENTERPOINT ENERGY":["CENTERPOINT ENERGY","CENTERPOINT PROPERTIES","SONNY CALLAHAN & ASSOCIATES LLC (ON BEHALF OF CENTERPOINT MANUFACTURING INC )"],
    "DISCOVERY":["DISCOVERY"],
    "BORGWARNER":["BORGWARNER","BORGWARNER INC.","ARMITAGE CONSULTING, LLC (0N BEHALF OF BORGWARNER, INC.)","BORGWARNER INC."],
    "TARGA RESOURCES":["TARGA RESOURCES"],
    "ALLY FINANCIAL":["ALLY FINANCIAL","ALLY FINANCIAL INC."],
    "SUNTRUST BANKS":["SUNTRUST BANKS"],
    "IQVIA HOLDINGS":["IQVIA HOLDINGS"],
    "AMERICAN FAMILY INSURANCE GROUP":["AMERICAN FAMILY INSURANCE GROUP"],
    "DELEK US HOLDINGS":["DELEK US HOLDINGS","DELEK US HOLDINGS, INC."],
    "NAVISTAR INTERNATIONAL":["NAVISTAR INTERNATIONAL"],
    "CHESAPEAKE ENERGY":["CHESAPEAKE ENERGY","CHESAPEAKE ENERGY CORPORATION"],
    "UNITED NATURAL FOODS":["UNITED NATURAL FOODS","UNITED NATURAL FOODS, INC."],
    "LEIDOS HOLDINGS":["LEIDOS HOLDINGS"],
    "PULTEGROUP":["PULTEGROUP","PULTEGROUP INC"],
    "EASTMAN CHEMICAL":["EASTMAN CHEMICAL","EASTMAN CHEMICAL COMPANY"],
    "REPUBLIC SERVICES":["REPUBLIC SERVICES"],
    "MOHAWK INDUSTRIES":["MOHAWK INDUSTRIES"],
    "SONIC AUTOMOTIVE":["SONIC AUTOMOTIVE"],
    "OWENS & MINOR":["OWENS & MINOR","OWENS & MINOR, INC."],
    "XEROX":["XEROX","XEROX CORPORATION"],
    "BOSTON SCIENTIFIC":["BOSTON SCIENTIFIC","BOSTON SCIENTIFIC CORPORATION"],
    "DCP MIDSTREAM":["DCP MIDSTREAM"],
    "AUTOLIV":["AUTOLIV","AUTOLIV ASP, INC."],
    "INTERPUBLIC GROUP":["INTERPUBLIC GROUP","INTERPUBLIC GROUP OF COMPANIES"],
    "PUBLIC SERVICE ENTERPRISE GROUP":["PUBLIC SERVICE ENTERPRISE GROUP"],
    "PVH":["PVH","PVH CORP."],
    "MOSAIC":["MOSAIC","MOSAIC MICROSYSTEMS","THE MOSAIC COMPANY"],
    "ADVANCE AUTO PARTS":["ADVANCE AUTO PARTS","ADVANCE AUTO PARTS, INC."],
    "ALTICE USA":["ALTICE USA"],
    "HORMEL FOODS":["HORMEL FOODS","HORMEL FOODS CORPORATION"],
    "O'REILLY AUTOMOTIVE":["O'REILLY AUTOMOTIVE"],
    "CALPINE":["CALPINE","CALPINE CORP"],
    "HERTZ GLOBAL HOLDINGS":["HERTZ GLOBAL HOLDINGS","THE HERTZ CORPORATION"],
    "FIRST DATA":["FIRST DATA","FIRST DATA CORPORATION","CARD & ASSOCIATES (ON BEHALF OF FIRST DATA CORP )"],
    "PIONEER NATURAL RESOURCES":["PIONEER NATURAL RESOURCES"],
    "COTY":["COTY"],
    "AGCO":["AGCO","AGCO CORPORATION"],
    "MUTUAL OF OMAHA INSURANCE":["MUTUAL OF OMAHA INSURANCE"],
    "VISTRA ENERGY":["VISTRA ENERGY","VISTRA ENERGY CORP (FORMERLY ENERGY FUTURE HOLDINGS)"],
    "AVIS BUDGET GROUP":["AVIS BUDGET GROUP","AVIS BUDGET GROUP, INC."],
    "ADOBE":["ADOBE","ADOBE INC."],
    "PETER KIEWIT SONS'":["PETER KIEWIT SONS'"],
    "NEWS CORP.":["NEWS CORP."],
    "BRIGHTHOUSE FINANCIAL":["BRIGHTHOUSE FINANCIAL"],
    "VOYA FINANCIAL":["VOYA FINANCIAL"],
    "AIR PRODUCTS & CHEMICALS":["AIR PRODUCTS & CHEMICALS"],
    "HILTON WORLDWIDE HOLDINGS":["HILTON WORLDWIDE HOLDINGS","HILTON WORLDWIDE","HILTON GRAND VACATIONS"],
    "GAMESTOP":["GAMESTOP"],
    "VERITIV":["VERITIV"],
    "WILLIAMS":["WILLIAMS"],
    "CAMPBELL SOUP":["CAMPBELL SOUP","CAMPBELL SOUP COMPANY"],
    "ROCKWELL COLLINS":["ROCKWELL COLLINS","ROCKWELL COLLINS (FORMERLY ITAC)"],
    "THRIVENT FINANCIAL FOR LUTHERANS":["THRIVENT FINANCIAL FOR LUTHERANS"],
    "WESTLAKE CHEMICAL":["WESTLAKE CHEMICAL","WESTLAKE CHEMICAL PARTNERS LP"],
    "UNIVAR":["UNIVAR"],
    "J.B. HUNT TRANSPORT SERVICES":["J.B. HUNT TRANSPORT SERVICES"],
    "FRONTIER COMMUNICATIONS":["FRONTIER COMMUNICATIONS"],
    "JONES FINANCIAL (EDWARD JONES)":["JONES FINANCIAL (EDWARD JONES)"],
    "NATIONAL OILWELL VARCO":["NATIONAL OILWELL VARCO"],
    "EVERSOURCE ENERGY":["EVERSOURCE ENERGY"],
    "DICK'S SPORTING GOODS":["DICK'S SPORTING GOODS","DICK'S SPORTING GOODS, INC."],
    "GENWORTH FINANCIAL":["GENWORTH FINANCIAL","GENWORTH FINANCIAL, INC."],
    "FIDELITY NATIONAL INFORMATION SERVICES":["FIDELITY NATIONAL INFORMATION SERVICES","FIDELITY CHARITABLE GIFT FUND","FIDELITY SECURITY LIFE INSURANCE COMPANY"],
    "YUM CHINA HOLDINGS":["YUM CHINA HOLDINGS","YUM CHINA HOLDINGS, INC."],
    "RYDER SYSTEM":["RYDER SYSTEM"],
    "ANIXTER INTERNATIONAL":["ANIXTER INTERNATIONAL"],
    "CAESARS ENTERTAINMENT":["CAESARS ENTERTAINMENT"],
    "MASCO":["MASCO","MASCO CORPORATION","MEDICAL ACADEMIC AND SCIENTIFIC COMMUNITY ORGANIZATION, INC. (MASCO)","MASCOMA CORP"],
    "THOR INDUSTRIES":["THOR INDUSTRIES"],
    "ALASKA AIR GROUP":["ALASKA AIR GROUP"],
    "AMPHENOL":["AMPHENOL","AMPHENOL BORISCH TECHNOLOGIES (FORMERLY BORISCH MANUFACTURING CORPORATION)"],
    "WESCO INTERNATIONAL":["WESCO INTERNATIONAL","WESCO INTERNATIONAL, INC."],
    "HUNTINGTON INGALLS INDUSTRIES":["HUNTINGTON INGALLS INDUSTRIES","DAHLBERG STRATEGIC ON BEHALF OF HUNTINGTON INGALLS"],
    "JEFFERIES FINANCIAL GROUP":["JEFFERIES FINANCIAL GROUP"],
    "DANA":["DANA"],
    "EXPEDITORS INTL. OF WASHINGTON":["EXPEDITORS INTL. OF WASHINGTON"],
    "EMCOR GROUP":["EMCOR GROUP"],
    "DARDEN RESTAURANTS":["DARDEN RESTAURANTS"],
    "SPARTANNASH":["SPARTANNASH"],
    "ASSURANT":["ASSURANT","ASSURANT, INC."],
    "UNITED RENTALS":["UNITED RENTALS"],
    "LIBERTY MEDIA":["LIBERTY MEDIA","LIBERTY MEDIA CORPORATION"],
    "ERIE INSURANCE GROUP":["ERIE INSURANCE GROUP"],
    "AUTO-OWNERS INSURANCE":["AUTO-OWNERS INSURANCE"],
    "CHENIERE ENERGY":["CHENIERE ENERGY","CHENIERE ENERGY, INC."],
    "FIFTH THIRD BANCORP":["FIFTH THIRD BANCORP"],
    "FOOT LOCKER":["FOOT LOCKER"],
    "CONAGRA BRANDS":["CONAGRA BRANDS","CONAGRA"],
    "ZIMMER BIOMET HOLDINGS":["ZIMMER BIOMET HOLDINGS","ZIMMER","SOC-USA, A DAY & ZIMMERMAN COMPANY"],
    "TRACTOR SUPPLY":["TRACTOR SUPPLY","TRACTOR SUPPLY COMPANY"],
    "BERRY GLOBAL GROUP":["BERRY GLOBAL GROUP"],
    "ALLIANCE DATA SYSTEMS":["ALLIANCE DATA SYSTEMS"],
    "HERSHEY":["HERSHEY","HERSHEY FOODS CORP","HERSHEY ENTERTAINMENT & RESORTS COMPANY FORMERLY KNOWN AS HERSHEY TRUST COMPANY","HERSHEY ENTERTAINMENT & RESORTS COMPANY"],
    "PPL":["PPL","PPL CORPORATION"],
    "DEAN FOODS":["DEAN FOODS","DEAN FOODS CO","OFFICIAL COMMITTEE OF UNSECURED CREDITORS OF SOUTHERN FOODS DBA DEAN FOODS","DEAN FOODS AD HOC BONDHOLDERS GROUP"],
    "BUILDERS FIRSTSOURCE":["BUILDERS FIRSTSOURCE"],
    "OSHKOSH":["OSHKOSH","OSHKOSH CORPORATION"],
    "ENLINK MIDSTREAM":["ENLINK MIDSTREAM"],
    "W.R. BERKLEY":["W.R. BERKLEY","W.R. BERKLEY CORPORATION"],
    "WEC ENERGY GROUP":["WEC ENERGY GROUP"],
    "JETBLUE AIRWAYS":["JETBLUE AIRWAYS","JTR STRATEGIES ON BEHALF OF JETBLUE AIRWAYS CORPORATION","JETBLUE AIRWAYS CORPORATION"],
    "UGI":["UGI","UGI UTILITIES"],
    "A-MARK PRECIOUS METALS":["A-MARK PRECIOUS METALS"],
    "FIDELITY NATIONAL FINANCIAL":["FIDELITY NATIONAL FINANCIAL"],
    "CONSTELLATION BRANDS":["CONSTELLATION BRANDS","CONSTELLATION BRANDS BEER DIVISION (FORMERLY KNOWN AS CROWN IMPORTS)","CONSTELLATION BRANDS, INC."],
    "QUEST DIAGNOSTICS":["QUEST DIAGNOSTICS","QUEST DIAGNOSTICS INCORPORATED"],
    "ACTIVISION BLIZZARD":["ACTIVISION BLIZZARD","ACTIVISION BLIZZARD, INC."],
    "WEYERHAEUSER":["WEYERHAEUSER","WEYERHAEUSER COMPANY"],
    "RAYMOND JAMES FINANCIAL":["RAYMOND JAMES FINANCIAL"],
    "CASEY'S GENERAL STORES":["CASEY'S GENERAL STORES"],
    "KEURIG DR PEPPER":["KEURIG DR PEPPER","KEURIG DR PEPPER INC."],
    "AMERICAN TOWER":["AMERICAN TOWER","AMERICAN TOWER CORPORATION"],
    "APACHE":["APACHE","APACHE CORPORATION"],
    "DOVER":["DOVER","DOVER INTL SPEEDWAY","DOVER CORP","DOVER KNOLLS DEVELOPMENT COMPANY II, LLC"],
    "KEYCORP":["KEYCORP"],
    "J.M. SMUCKER":["J.M. SMUCKER","THE J.M. SMUCKER COMPANY"],
    "CITIZENS FINANCIAL GROUP":["CITIZENS FINANCIAL GROUP","CITIZENS FINANCIAL GROUP INC"],
    "MOTOROLA SOLUTIONS":["MOTOROLA SOLUTIONS","MOTOROLA SOLUTIONS, INC."],
    "MAGELLAN HEALTH":["MAGELLAN HEALTH","MAGELLAN HEALTH SERVICES"],
    "AMERICAN AXLE & MANUFACTURING":["AMERICAN AXLE & MANUFACTURING"],
    "NEWMONT GOLDCORP":["NEWMONT GOLDCORP"],
    "SPIRIT AEROSYSTEMS HOLDINGS":["SPIRIT AEROSYSTEMS HOLDINGS"],
    "WESTERN & SOUTHERN FINANCIAL GROUP":["WESTERN & SOUTHERN FINANCIAL GROUP"],
    "FORTIVE":["FORTIVE"],
    "GRAYBAR ELECTRIC":["GRAYBAR ELECTRIC"],
    "NVR":["NVR","NVR INC"],
    "AVERY DENNISON":["AVERY DENNISON"],
    "CELANESE":["CELANESE","CELANESE CORP"],
    "AMERICAN FINANCIAL GROUP":["AMERICAN FINANCIAL GROUP"],
    "TOLL BROTHERS":["TOLL BROTHERS","TOLL BROTHERS INC"],
    "SANMINA":["SANMINA","SANMINA CORPORATION"],
    "INSIGHT ENTERPRISES":["INSIGHT ENTERPRISES"],
    "OWENS CORNING":["OWENS CORNING","OWENS CORNING FIREBOARD ASBESTOS PERSONAL INJURY"],
    "PACKAGING CORP. OF AMERICA":["PACKAGING CORP. OF AMERICA"],
    "TRAVELCENTERS OF AMERICA":["TRAVELCENTERS OF AMERICA","TRAVELCENTERS OF AMERICA INC."],
    "OLIN":["OLIN","OLIN CORPORATION"],
    "ARTHUR J. GALLAGHER":["ARTHUR J. GALLAGHER"],
    "MASTEC":["MASTEC"],
    "ALLEGHANY":["ALLEGHANY","ALLEGHANY COUNTY ECONOMIC DEVELOPMENT CORPORATION","ALLEGHANY COUNTY","ALLEGHANY PROPERTIES"],
    "OWENS-ILLINOIS":["OWENS-ILLINOIS","OWENS-ILLINOIS INC"],
    "ASBURY AUTOMOTIVE GROUP":["ASBURY AUTOMOTIVE GROUP"],
    "CMS ENERGY":["CMS ENERGY","CMS ENERGY CORP"],
    "MARKEL":["MARKEL","MARKEL CORPORATION"],
    "BLACKSTONE GROUP":["BLACKSTONE GROUP"],
    "AK STEEL HOLDING":["AK STEEL HOLDING","AK STEEL HOLDING CORPORATION"],
    "HANESBRANDS":["HANESBRANDS","HANESBRANDS INC"],
    "R.R. DONNELLEY & SONS":["R.R. DONNELLEY & SONS"],
    "WAYFAIR":["WAYFAIR"],
    "REGIONS FINANCIAL":["REGIONS FINANCIAL","REGIONS FINANCIAL CORPORATION"],
    "WYNN RESORTS":["WYNN RESORTS","WYNN RESORTS, LTD."],
    "ULTA BEAUTY":["ULTA BEAUTY"],
    "REGENERON PHARMACEUTICALS":["REGENERON PHARMACEUTICALS","REGENERON PHARMACEUTICALS, INC."],
    "BURLINGTON STORES":["BURLINGTON STORES"],
    "ROCKWELL AUTOMATION":["ROCKWELL AUTOMATION"],
    "NORTHERN TRUST":["NORTHERN TRUST"],
    "CHEMOURS":["CHEMOURS","THE CHEMOURS COMPANY"],
    "SEABOARD":["SEABOARD","SEABOARD CORPORATION"],
    "MARATHON OIL":["MARATHON OIL","MARATHON OIL COMPANY"],
    "ASCENA RETAIL GROUP":["ASCENA RETAIL GROUP"],
    "DILLARD'S":["DILLARD'S","DILLARD'S INC"],
    "CINTAS":["CINTAS","CINTAS CORPORATION"],
    "ADVANCED MICRO DEVICES":["ADVANCED MICRO DEVICES"],
    "HESS":["HESS","HESS CORPORATION"],
    "M&T BANK CORP.":["M&T BANK CORP.","M&T BANK CORPORATION"],
    "ABM INDUSTRIES":["ABM INDUSTRIES","ABM INDUSTRIES, INC."],
    "BEACON ROOFING SUPPLY":["BEACON ROOFING SUPPLY"],
    "NCR":["NCR","NCR CORP"],
    "IHEARTMEDIA":["IHEARTMEDIA","IHEARTMEDIA INC"],
    "FRANKLIN RESOURCES":["FRANKLIN RESOURCES","FRANKLIN RESOURCES, INC."],
    "AMEREN":["AMEREN","AMEREN SERVICES"],
    "INTERCONTINENTAL EXCHANGE":["INTERCONTINENTAL EXCHANGE"],
    "S&P GLOBAL":["S&P GLOBAL"],
    "POST HOLDINGS":["POST HOLDINGS","POST HOLDINGS, INC."],
    "ANALOG DEVICES":["ANALOG DEVICES","ANALOG DEVICES, INC."],
    "RALPH LAUREN":["RALPH LAUREN","POLO RALPH LAUREN"],
    "L3HARRIS TECHNOLOGIES":["L3HARRIS TECHNOLOGIES"],
    "BOOZ ALLEN HAMILTON":["BOOZ ALLEN HAMILTON"],
    "POLARIS INDUSTRIES":["POLARIS INDUSTRIES"],
    "CLOROX":["CLOROX","CLOROX SERVICES COMPANY"],
    "REALOGY HOLDINGS":["REALOGY HOLDINGS"],
    "HD SUPPLY HOLDINGS":["HD SUPPLY HOLDINGS"],
    "GRAPHIC PACKAGING HOLDING":["GRAPHIC PACKAGING HOLDING"],
    "OLD REPUBLIC INTERNATIONAL":["OLD REPUBLIC INTERNATIONAL"],
    "INTUIT":["INTUIT","INTUIT, INC. AND AFFILIATES (FORMERLY INTUIT, INC.)"],
    "NETAPP":["NETAPP"],
    "TAPESTRY":["TAPESTRY","TAPESTRY, INC."],
    "ON SEMICONDUCTOR":["ON SEMICONDUCTOR"],
    "INGREDION":["INGREDION"],
    "ZOETIS":["ZOETIS","ZOETIS INC."],
    "FISERV":["FISERV"],
    "TREEHOUSE FOODS":["TREEHOUSE FOODS","TREEHOUSE FOODS, INC."],
    "ROBERT HALF INTERNATIONAL":["ROBERT HALF INTERNATIONAL","ROBERT HALF INTERNATIONAL, INC."],
    "FIRST AMERICAN FINANCIAL":["FIRST AMERICAN FINANCIAL","FIRST AMERICAN FINANCIAL CORPORATION"],
    "HARLEY-DAVIDSON":["HARLEY-DAVIDSON","HARLEY-DAVIDSON MOTOR COMPANY INC","HARLEY-DAVIDSON FINANCIAL SERVICES, INC."],
    "WINDSTREAM HOLDINGS":["WINDSTREAM HOLDINGS"],
    "YUM BRANDS":["YUM BRANDS"],
    "WILLIAMS-SONOMA":["WILLIAMS-SONOMA"],
    "SIMON PROPERTY GROUP":["SIMON PROPERTY GROUP","SIMON PROPERTY GROUP, INC."],
    "NAVIENT":["NAVIENT"],
    "WESTERN UNION":["WESTERN UNION"],
    "PEABODY ENERGY":["PEABODY ENERGY"],
    "LEVI STRAUSS":["LEVI STRAUSS","LEVI STRAUSS & CO"]
}


PAIRS_CSV = "/Users/vfigueroa/Library/CloudStorage/OneDrive-BowdoinCollege/Desktop/Prathit/Lobbying-Networks-Research/src/lobbyist_network/company_lobbyingfirm_pairs_116_2019.csv"   # your existing pairs file
EDGE_OUTPUT_PATH = "/Users/vfigueroa/Library/CloudStorage/OneDrive-BowdoinCollege/Desktop/Prathit/Lobbying-Networks-Research/src/lobbyist_network/company_affiliation_edges_116_2019.csv"

GML_OUTPUT_PATH = "/Users/vfigueroa/Library/CloudStorage/OneDrive-BowdoinCollege/Desktop/Prathit/Lobbying-Networks-Research/src/lobbyist_network/fortune500_shared_firms_116_2019.gml"
PNG_OUTPUT_PATH = "/Users/vfigueroa/Library/CloudStorage/OneDrive-BowdoinCollege/Desktop/Prathit/Lobbying-Networks-Research/src/lobbyist_network/fortune500_shared_firms_116_2019.png"

TOP_K = 20

def company_firm_affiliation_edges(pairs: pd.DataFrame) -> pd.DataFrame:
    """
    Build company-company edges where weight = number of shared lobbying firms (registrant_id).
    No itertools, no collections. Nested loops only.
    """
    firm_companies = (
        pairs.groupby("registrant_id")["company"]
        .apply(lambda s: sorted(set(s)))
        .to_dict()
    )

    edge_weights = {}

    for firm_id, comps in firm_companies.items():
        if len(comps) < 2:
            continue

        for i in range(len(comps)):
            for j in range(i + 1, len(comps)):
                a = comps[i]
                b = comps[j]
                key = (a, b)  # ordered because comps sorted
                edge_weights[key] = edge_weights.get(key, 0) + 1

    edges = pd.DataFrame(
        [(a, b, w) for (a, b), w in edge_weights.items()],
        columns=["source", "target", "weight"]
    ).sort_values("weight", ascending=False)

    edges.to_csv(EDGE_OUTPUT_PATH, index=False)
    print("Wrote edges:", EDGE_OUTPUT_PATH, "rows:", len(edges))
    return edges

def build_networkx_graph(edge_df: pd.DataFrame) -> nx.Graph:
    """Build undirected weighted graph from edge list."""
    G = nx.Graph()
    for _, row in edge_df.iterrows():
        G.add_edge(row["source"], row["target"], weight=int(row["weight"]))
    nx.write_gml(G, GML_OUTPUT_PATH)
    print("Saved GML:", GML_OUTPUT_PATH)
    return G

def extract_top_k_subgraph(G: nx.Graph, k: int) -> nx.Graph:
    """Top-k nodes by weighted degree (strength)."""
    strengths = {n: G.degree(n, weight="weight") for n in G.nodes()}
    top_nodes = [n for n, _ in sorted(strengths.items(), key=lambda x: x[1], reverse=True)[:k]]
    return G.subgraph(top_nodes).copy()

def plot_network(H: nx.Graph, title: str, out_png: str):
    """Plot a graph with node size by weighted degree and edge width by weight."""
    if H.number_of_nodes() == 0:
        print("Graph is empty; nothing to plot.")
        return

    pos = nx.circular_layout(H)

    # node sizes by weighted degree
    strengths = np.array([H.degree(n, weight="weight") for n in H.nodes()])
    node_sizes = 800 + 3000 * (strengths - strengths.min()) / (strengths.max() - strengths.min() + 1)

    # edge widths by weight
    edges = list(H.edges())
    weights = np.array([H[u][v]["weight"] for u, v in edges]) if edges else np.array([])
    edge_widths = 1 + 20 * (weights - weights.min()) / (weights.max() - weights.min() + 1) if weights.size else []

    fig, ax = plt.subplots(figsize=(16, 16))

    nx.draw_networkx_nodes(
        H, pos,
        node_size=node_sizes,
        edgecolors="black",
        linewidths=1.2,
        ax=ax
    )

    if edges:
        nx.draw_networkx_edges(H, pos, width=edge_widths, alpha=0.7, ax=ax)

    nx.draw_networkx_labels(
        H, pos,
        font_size=10,
        bbox=dict(facecolor="white", edgecolor="none", alpha=0.7),
        ax=ax
    )

    ax.set_title(title, fontsize=16, fontweight="bold")
    ax.axis("off")

    plt.tight_layout()
    plt.savefig(out_png, dpi=300, bbox_inches="tight")
    print("Saved PNG:", out_png)

def main():
    # Load your prebuilt pairs
    pairs = pd.read_csv(PAIRS_CSV, dtype=str)

    # Safety de-dupe so you don't double-count a firm's link to a company
    pairs = (
        pairs[["company", "registrant_id", "registrant_name"]]
        .dropna(subset=["company", "registrant_id"])
        .drop_duplicates()
        .sort_values(["company", "registrant_id"])
        .drop_duplicates(["company", "registrant_id"])
    )

    print("Pairs rows:", len(pairs))
    print("Unique companies:", pairs["company"].nunique())
    print("Unique firms:", pairs["registrant_id"].nunique())

    # Build edges and graph
    edge_df = company_firm_affiliation_edges(pairs)
    G = build_networkx_graph(edge_df)

    # Plot either full graph or top-k subgraph
    if TOP_K is not None:
        H = extract_top_k_subgraph(G, TOP_K)
        plot_network(
            H,
            title=f"Top {TOP_K} Fortune 500 Shared Lobbying Firms Network (116th, 2019)",
            out_png=PNG_OUTPUT_PATH
        )
    else:
        plot_network(
            G,
            title="Fortune 500 Shared Lobbying Firms Network (116th, 2019)",
            out_png=PNG_OUTPUT_PATH
        )

if __name__ == "__main__":
    main()